### ISSUE TITLE
Love The Webdriver But It Has Had Issues These Last Few Months

### ISSUE THREAD

**Issue by dr-NHA** [miksch123/WiniumWebdriver#1]
Please Bring The Project Back From The Dead :)
Alerts Need Fixing For Both Chrome And Firefox :)

**Comment by miksch123** [comment]
I am sorry if I have to disappoint you, but the change I did was to see if
the winium driver was good fit for my project. It turns out that it was
not. Instead I opted into using Microsoft's UIA API to do all my Automation
work. It works quite solid hence there was no need to use winium anymore.

dr-NHA ***@***.***> schrieb am Di., 27. Dez. 2022, 23:12:
